[default]
#FastAPI
fastapi_title = "DANS License API Service"
fastapi_description = "This service supports .."

licences_dir = "../resources/licences"
licences_list_file = "../resources/licences/licences-list.json"
#logs
log_file = "../logs/dls.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"
#Note: below the list of logging level
#CRITICAL = 50
#ERROR = 40
#WARNING = 30
#INFO = 20
#DEBUG = 10

[development]

[staging]

[testing]

[production]